package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputFieldWriter;
import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import type.CustomType;

public final class BacklogMutation implements Mutation<BacklogMutation.Data, BacklogMutation.Data, BacklogMutation.Variables> {
  public static final String OPERATION_ID = "9b547fd30b9beac15f5570bf5275bb39704ef22a69d982bf4b974aa1a13d6a1f";

  public static final String QUERY_DOCUMENT = "mutation Backlog($id: String!, $idProject: String!, $idEpic: String!, $assignee: String!, $name: String!, $status: String!, $description: String!, $createddate: Date!, $createdby: String!) {\n"
      + "  createBacklog(id: $id, idProject: $idProject, idEpic: $idEpic, assignee: $assignee, name: $name, status: $status, description: $description, createddate: $createddate, createdby: $createdby) {\n"
      + "    __typename\n"
      + "    id\n"
      + "    idProject\n"
      + "    idEpic\n"
      + "    assignee\n"
      + "    name\n"
      + "    status\n"
      + "    description\n"
      + "    createddate\n"
      + "    createdby\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "Backlog";
    }
  };

  private final BacklogMutation.Variables variables;

  public BacklogMutation(@NotNull String id, @NotNull String idProject, @NotNull String idEpic,
      @NotNull String assignee, @NotNull String name, @NotNull String status,
      @NotNull String description, @NotNull Date createddate, @NotNull String createdby) {
    Utils.checkNotNull(id, "id == null");
    Utils.checkNotNull(idProject, "idProject == null");
    Utils.checkNotNull(idEpic, "idEpic == null");
    Utils.checkNotNull(assignee, "assignee == null");
    Utils.checkNotNull(name, "name == null");
    Utils.checkNotNull(status, "status == null");
    Utils.checkNotNull(description, "description == null");
    Utils.checkNotNull(createddate, "createddate == null");
    Utils.checkNotNull(createdby, "createdby == null");
    variables = new BacklogMutation.Variables(id, idProject, idEpic, assignee, name, status, description, createddate, createdby);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public BacklogMutation.Data wrapData(BacklogMutation.Data data) {
    return data;
  }

  @Override
  public BacklogMutation.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    private @NotNull String id;

    private @NotNull String idProject;

    private @NotNull String idEpic;

    private @NotNull String assignee;

    private @NotNull String name;

    private @NotNull String status;

    private @NotNull String description;

    private @NotNull Date createddate;

    private @NotNull String createdby;

    Builder() {
    }

    public Builder id(@NotNull String id) {
      this.id = id;
      return this;
    }

    public Builder idProject(@NotNull String idProject) {
      this.idProject = idProject;
      return this;
    }

    public Builder idEpic(@NotNull String idEpic) {
      this.idEpic = idEpic;
      return this;
    }

    public Builder assignee(@NotNull String assignee) {
      this.assignee = assignee;
      return this;
    }

    public Builder name(@NotNull String name) {
      this.name = name;
      return this;
    }

    public Builder status(@NotNull String status) {
      this.status = status;
      return this;
    }

    public Builder description(@NotNull String description) {
      this.description = description;
      return this;
    }

    public Builder createddate(@NotNull Date createddate) {
      this.createddate = createddate;
      return this;
    }

    public Builder createdby(@NotNull String createdby) {
      this.createdby = createdby;
      return this;
    }

    public BacklogMutation build() {
      Utils.checkNotNull(id, "id == null");
      Utils.checkNotNull(idProject, "idProject == null");
      Utils.checkNotNull(idEpic, "idEpic == null");
      Utils.checkNotNull(assignee, "assignee == null");
      Utils.checkNotNull(name, "name == null");
      Utils.checkNotNull(status, "status == null");
      Utils.checkNotNull(description, "description == null");
      Utils.checkNotNull(createddate, "createddate == null");
      Utils.checkNotNull(createdby, "createdby == null");
      return new BacklogMutation(id, idProject, idEpic, assignee, name, status, description, createddate, createdby);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull String id;

    private final @NotNull String idProject;

    private final @NotNull String idEpic;

    private final @NotNull String assignee;

    private final @NotNull String name;

    private final @NotNull String status;

    private final @NotNull String description;

    private final @NotNull Date createddate;

    private final @NotNull String createdby;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull String id, @NotNull String idProject, @NotNull String idEpic,
        @NotNull String assignee, @NotNull String name, @NotNull String status,
        @NotNull String description, @NotNull Date createddate, @NotNull String createdby) {
      this.id = id;
      this.idProject = idProject;
      this.idEpic = idEpic;
      this.assignee = assignee;
      this.name = name;
      this.status = status;
      this.description = description;
      this.createddate = createddate;
      this.createdby = createdby;
      this.valueMap.put("id", id);
      this.valueMap.put("idProject", idProject);
      this.valueMap.put("idEpic", idEpic);
      this.valueMap.put("assignee", assignee);
      this.valueMap.put("name", name);
      this.valueMap.put("status", status);
      this.valueMap.put("description", description);
      this.valueMap.put("createddate", createddate);
      this.valueMap.put("createdby", createdby);
    }

    public @NotNull String id() {
      return id;
    }

    public @NotNull String idProject() {
      return idProject;
    }

    public @NotNull String idEpic() {
      return idEpic;
    }

    public @NotNull String assignee() {
      return assignee;
    }

    public @NotNull String name() {
      return name;
    }

    public @NotNull String status() {
      return status;
    }

    public @NotNull String description() {
      return description;
    }

    public @NotNull Date createddate() {
      return createddate;
    }

    public @NotNull String createdby() {
      return createdby;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeString("id", id);
          writer.writeString("idProject", idProject);
          writer.writeString("idEpic", idEpic);
          writer.writeString("assignee", assignee);
          writer.writeString("name", name);
          writer.writeString("status", status);
          writer.writeString("description", description);
          writer.writeCustom("createddate", CustomType.DATE, createddate);
          writer.writeString("createdby", createdby);
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forObject("createBacklog", "createBacklog", new UnmodifiableMapBuilder<String, Object>(9)
      .put("id", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "id")
        .build())
      .put("idProject", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "idProject")
        .build())
      .put("idEpic", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "idEpic")
        .build())
      .put("assignee", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "assignee")
        .build())
      .put("name", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "name")
        .build())
      .put("status", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "status")
        .build())
      .put("description", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "description")
        .build())
      .put("createddate", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "createddate")
        .build())
      .put("createdby", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "createdby")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable CreateBacklog createBacklog;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable CreateBacklog createBacklog) {
      this.createBacklog = createBacklog;
    }

    public @Nullable CreateBacklog createBacklog() {
      return this.createBacklog;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeObject($responseFields[0], createBacklog != null ? createBacklog.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "createBacklog=" + createBacklog
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.createBacklog == null) ? (that.createBacklog == null) : this.createBacklog.equals(that.createBacklog));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (createBacklog == null) ? 0 : createBacklog.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final CreateBacklog.Mapper createBacklogFieldMapper = new CreateBacklog.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final CreateBacklog createBacklog = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<CreateBacklog>() {
          @Override
          public CreateBacklog read(ResponseReader reader) {
            return createBacklogFieldMapper.map(reader);
          }
        });
        return new Data(createBacklog);
      }
    }
  }

  public static class CreateBacklog {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("idProject", "idProject", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("idEpic", "idEpic", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("assignee", "assignee", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("name", "name", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("status", "status", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("description", "description", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("createddate", "createddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("createdby", "createdby", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String id;

    final @Nullable String idProject;

    final @Nullable String idEpic;

    final @Nullable String assignee;

    final @Nullable String name;

    final @Nullable String status;

    final @Nullable String description;

    final @Nullable Date createddate;

    final @Nullable String createdby;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public CreateBacklog(@NotNull String __typename, @Nullable String id,
        @Nullable String idProject, @Nullable String idEpic, @Nullable String assignee,
        @Nullable String name, @Nullable String status, @Nullable String description,
        @Nullable Date createddate, @Nullable String createdby) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = id;
      this.idProject = idProject;
      this.idEpic = idEpic;
      this.assignee = assignee;
      this.name = name;
      this.status = status;
      this.description = description;
      this.createddate = createddate;
      this.createdby = createdby;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String id() {
      return this.id;
    }

    public @Nullable String idProject() {
      return this.idProject;
    }

    public @Nullable String idEpic() {
      return this.idEpic;
    }

    public @Nullable String assignee() {
      return this.assignee;
    }

    public @Nullable String name() {
      return this.name;
    }

    public @Nullable String status() {
      return this.status;
    }

    public @Nullable String description() {
      return this.description;
    }

    public @Nullable Date createddate() {
      return this.createddate;
    }

    public @Nullable String createdby() {
      return this.createdby;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
          writer.writeString($responseFields[2], idProject);
          writer.writeString($responseFields[3], idEpic);
          writer.writeString($responseFields[4], assignee);
          writer.writeString($responseFields[5], name);
          writer.writeString($responseFields[6], status);
          writer.writeString($responseFields[7], description);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[8], createddate);
          writer.writeString($responseFields[9], createdby);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "CreateBacklog{"
          + "__typename=" + __typename + ", "
          + "id=" + id + ", "
          + "idProject=" + idProject + ", "
          + "idEpic=" + idEpic + ", "
          + "assignee=" + assignee + ", "
          + "name=" + name + ", "
          + "status=" + status + ", "
          + "description=" + description + ", "
          + "createddate=" + createddate + ", "
          + "createdby=" + createdby
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof CreateBacklog) {
        CreateBacklog that = (CreateBacklog) o;
        return this.__typename.equals(that.__typename)
         && ((this.id == null) ? (that.id == null) : this.id.equals(that.id))
         && ((this.idProject == null) ? (that.idProject == null) : this.idProject.equals(that.idProject))
         && ((this.idEpic == null) ? (that.idEpic == null) : this.idEpic.equals(that.idEpic))
         && ((this.assignee == null) ? (that.assignee == null) : this.assignee.equals(that.assignee))
         && ((this.name == null) ? (that.name == null) : this.name.equals(that.name))
         && ((this.status == null) ? (that.status == null) : this.status.equals(that.status))
         && ((this.description == null) ? (that.description == null) : this.description.equals(that.description))
         && ((this.createddate == null) ? (that.createddate == null) : this.createddate.equals(that.createddate))
         && ((this.createdby == null) ? (that.createdby == null) : this.createdby.equals(that.createdby));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (id == null) ? 0 : id.hashCode();
        h *= 1000003;
        h ^= (idProject == null) ? 0 : idProject.hashCode();
        h *= 1000003;
        h ^= (idEpic == null) ? 0 : idEpic.hashCode();
        h *= 1000003;
        h ^= (assignee == null) ? 0 : assignee.hashCode();
        h *= 1000003;
        h ^= (name == null) ? 0 : name.hashCode();
        h *= 1000003;
        h ^= (status == null) ? 0 : status.hashCode();
        h *= 1000003;
        h ^= (description == null) ? 0 : description.hashCode();
        h *= 1000003;
        h ^= (createddate == null) ? 0 : createddate.hashCode();
        h *= 1000003;
        h ^= (createdby == null) ? 0 : createdby.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<CreateBacklog> {
      @Override
      public CreateBacklog map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        final String idProject = reader.readString($responseFields[2]);
        final String idEpic = reader.readString($responseFields[3]);
        final String assignee = reader.readString($responseFields[4]);
        final String name = reader.readString($responseFields[5]);
        final String status = reader.readString($responseFields[6]);
        final String description = reader.readString($responseFields[7]);
        final Date createddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[8]);
        final String createdby = reader.readString($responseFields[9]);
        return new CreateBacklog(__typename, id, idProject, idEpic, assignee, name, status, description, createddate, createdby);
      }
    }
  }
}
