package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputFieldWriter;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import type.CustomType;

public final class BacklogQuery implements Query<BacklogQuery.Data, BacklogQuery.Data, BacklogQuery.Variables> {
  public static final String OPERATION_ID = "28c3fb33f0b345d02277dc2d6375459d3ec4ac29cfc698ab26e50ff9d2be8dfc";

  public static final String QUERY_DOCUMENT = "query backlog($id: String!) {\n"
      + "  backlog(id: $id) {\n"
      + "    __typename\n"
      + "    id\n"
      + "    idSprint {\n"
      + "      __typename\n"
      + "      id\n"
      + "    }\n"
      + "    idEpic {\n"
      + "      __typename\n"
      + "      id\n"
      + "    }\n"
      + "    name\n"
      + "    status\n"
      + "    description\n"
      + "    assignee {\n"
      + "      __typename\n"
      + "      email\n"
      + "    }\n"
      + "    createddate\n"
      + "    createdby {\n"
      + "      __typename\n"
      + "      nama\n"
      + "    }\n"
      + "    modifieddate\n"
      + "    modifiedby {\n"
      + "      __typename\n"
      + "      nama\n"
      + "    }\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "backlog";
    }
  };

  private final BacklogQuery.Variables variables;

  public BacklogQuery(@NotNull String id) {
    Utils.checkNotNull(id, "id == null");
    variables = new BacklogQuery.Variables(id);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public BacklogQuery.Data wrapData(BacklogQuery.Data data) {
    return data;
  }

  @Override
  public BacklogQuery.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    private @NotNull String id;

    Builder() {
    }

    public Builder id(@NotNull String id) {
      this.id = id;
      return this;
    }

    public BacklogQuery build() {
      Utils.checkNotNull(id, "id == null");
      return new BacklogQuery(id);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull String id;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull String id) {
      this.id = id;
      this.valueMap.put("id", id);
    }

    public @NotNull String id() {
      return id;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeString("id", id);
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forList("backlog", "backlog", new UnmodifiableMapBuilder<String, Object>(1)
      .put("id", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "id")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable List<Backlog> backlog;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable List<Backlog> backlog) {
      this.backlog = backlog;
    }

    public @Nullable List<Backlog> backlog() {
      return this.backlog;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], backlog, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Backlog) item).marshaller());
              }
            }
          });
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "backlog=" + backlog
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.backlog == null) ? (that.backlog == null) : this.backlog.equals(that.backlog));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (backlog == null) ? 0 : backlog.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final Backlog.Mapper backlogFieldMapper = new Backlog.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final List<Backlog> backlog = reader.readList($responseFields[0], new ResponseReader.ListReader<Backlog>() {
          @Override
          public Backlog read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<Backlog>() {
              @Override
              public Backlog read(ResponseReader reader) {
                return backlogFieldMapper.map(reader);
              }
            });
          }
        });
        return new Data(backlog);
      }
    }
  }

  public static class Backlog {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("idSprint", "idSprint", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("idEpic", "idEpic", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("name", "name", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("status", "status", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("description", "description", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("assignee", "assignee", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("createddate", "createddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("createdby", "createdby", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("modifieddate", "modifieddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("modifiedby", "modifiedby", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @NotNull String id;

    final @Nullable IdSprint idSprint;

    final @Nullable IdEpic idEpic;

    final @Nullable String name;

    final @Nullable String status;

    final @Nullable String description;

    final @Nullable Assignee assignee;

    final @Nullable Date createddate;

    final @Nullable Createdby createdby;

    final @Nullable Date modifieddate;

    final @Nullable Modifiedby modifiedby;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Backlog(@NotNull String __typename, @NotNull String id, @Nullable IdSprint idSprint,
        @Nullable IdEpic idEpic, @Nullable String name, @Nullable String status,
        @Nullable String description, @Nullable Assignee assignee, @Nullable Date createddate,
        @Nullable Createdby createdby, @Nullable Date modifieddate,
        @Nullable Modifiedby modifiedby) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = Utils.checkNotNull(id, "id == null");
      this.idSprint = idSprint;
      this.idEpic = idEpic;
      this.name = name;
      this.status = status;
      this.description = description;
      this.assignee = assignee;
      this.createddate = createddate;
      this.createdby = createdby;
      this.modifieddate = modifieddate;
      this.modifiedby = modifiedby;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull String id() {
      return this.id;
    }

    public @Nullable IdSprint idSprint() {
      return this.idSprint;
    }

    public @Nullable IdEpic idEpic() {
      return this.idEpic;
    }

    public @Nullable String name() {
      return this.name;
    }

    public @Nullable String status() {
      return this.status;
    }

    public @Nullable String description() {
      return this.description;
    }

    public @Nullable Assignee assignee() {
      return this.assignee;
    }

    public @Nullable Date createddate() {
      return this.createddate;
    }

    public @Nullable Createdby createdby() {
      return this.createdby;
    }

    public @Nullable Date modifieddate() {
      return this.modifieddate;
    }

    public @Nullable Modifiedby modifiedby() {
      return this.modifiedby;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
          writer.writeObject($responseFields[2], idSprint != null ? idSprint.marshaller() : null);
          writer.writeObject($responseFields[3], idEpic != null ? idEpic.marshaller() : null);
          writer.writeString($responseFields[4], name);
          writer.writeString($responseFields[5], status);
          writer.writeString($responseFields[6], description);
          writer.writeObject($responseFields[7], assignee != null ? assignee.marshaller() : null);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[8], createddate);
          writer.writeObject($responseFields[9], createdby != null ? createdby.marshaller() : null);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[10], modifieddate);
          writer.writeObject($responseFields[11], modifiedby != null ? modifiedby.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Backlog{"
          + "__typename=" + __typename + ", "
          + "id=" + id + ", "
          + "idSprint=" + idSprint + ", "
          + "idEpic=" + idEpic + ", "
          + "name=" + name + ", "
          + "status=" + status + ", "
          + "description=" + description + ", "
          + "assignee=" + assignee + ", "
          + "createddate=" + createddate + ", "
          + "createdby=" + createdby + ", "
          + "modifieddate=" + modifieddate + ", "
          + "modifiedby=" + modifiedby
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Backlog) {
        Backlog that = (Backlog) o;
        return this.__typename.equals(that.__typename)
         && this.id.equals(that.id)
         && ((this.idSprint == null) ? (that.idSprint == null) : this.idSprint.equals(that.idSprint))
         && ((this.idEpic == null) ? (that.idEpic == null) : this.idEpic.equals(that.idEpic))
         && ((this.name == null) ? (that.name == null) : this.name.equals(that.name))
         && ((this.status == null) ? (that.status == null) : this.status.equals(that.status))
         && ((this.description == null) ? (that.description == null) : this.description.equals(that.description))
         && ((this.assignee == null) ? (that.assignee == null) : this.assignee.equals(that.assignee))
         && ((this.createddate == null) ? (that.createddate == null) : this.createddate.equals(that.createddate))
         && ((this.createdby == null) ? (that.createdby == null) : this.createdby.equals(that.createdby))
         && ((this.modifieddate == null) ? (that.modifieddate == null) : this.modifieddate.equals(that.modifieddate))
         && ((this.modifiedby == null) ? (that.modifiedby == null) : this.modifiedby.equals(that.modifiedby));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= id.hashCode();
        h *= 1000003;
        h ^= (idSprint == null) ? 0 : idSprint.hashCode();
        h *= 1000003;
        h ^= (idEpic == null) ? 0 : idEpic.hashCode();
        h *= 1000003;
        h ^= (name == null) ? 0 : name.hashCode();
        h *= 1000003;
        h ^= (status == null) ? 0 : status.hashCode();
        h *= 1000003;
        h ^= (description == null) ? 0 : description.hashCode();
        h *= 1000003;
        h ^= (assignee == null) ? 0 : assignee.hashCode();
        h *= 1000003;
        h ^= (createddate == null) ? 0 : createddate.hashCode();
        h *= 1000003;
        h ^= (createdby == null) ? 0 : createdby.hashCode();
        h *= 1000003;
        h ^= (modifieddate == null) ? 0 : modifieddate.hashCode();
        h *= 1000003;
        h ^= (modifiedby == null) ? 0 : modifiedby.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Backlog> {
      final IdSprint.Mapper idSprintFieldMapper = new IdSprint.Mapper();

      final IdEpic.Mapper idEpicFieldMapper = new IdEpic.Mapper();

      final Assignee.Mapper assigneeFieldMapper = new Assignee.Mapper();

      final Createdby.Mapper createdbyFieldMapper = new Createdby.Mapper();

      final Modifiedby.Mapper modifiedbyFieldMapper = new Modifiedby.Mapper();

      @Override
      public Backlog map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        final IdSprint idSprint = reader.readObject($responseFields[2], new ResponseReader.ObjectReader<IdSprint>() {
          @Override
          public IdSprint read(ResponseReader reader) {
            return idSprintFieldMapper.map(reader);
          }
        });
        final IdEpic idEpic = reader.readObject($responseFields[3], new ResponseReader.ObjectReader<IdEpic>() {
          @Override
          public IdEpic read(ResponseReader reader) {
            return idEpicFieldMapper.map(reader);
          }
        });
        final String name = reader.readString($responseFields[4]);
        final String status = reader.readString($responseFields[5]);
        final String description = reader.readString($responseFields[6]);
        final Assignee assignee = reader.readObject($responseFields[7], new ResponseReader.ObjectReader<Assignee>() {
          @Override
          public Assignee read(ResponseReader reader) {
            return assigneeFieldMapper.map(reader);
          }
        });
        final Date createddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[8]);
        final Createdby createdby = reader.readObject($responseFields[9], new ResponseReader.ObjectReader<Createdby>() {
          @Override
          public Createdby read(ResponseReader reader) {
            return createdbyFieldMapper.map(reader);
          }
        });
        final Date modifieddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[10]);
        final Modifiedby modifiedby = reader.readObject($responseFields[11], new ResponseReader.ObjectReader<Modifiedby>() {
          @Override
          public Modifiedby read(ResponseReader reader) {
            return modifiedbyFieldMapper.map(reader);
          }
        });
        return new Backlog(__typename, id, idSprint, idEpic, name, status, description, assignee, createddate, createdby, modifieddate, modifiedby);
      }
    }
  }

  public static class IdSprint {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, false, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @NotNull String id;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public IdSprint(@NotNull String __typename, @NotNull String id) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = Utils.checkNotNull(id, "id == null");
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull String id() {
      return this.id;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "IdSprint{"
          + "__typename=" + __typename + ", "
          + "id=" + id
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof IdSprint) {
        IdSprint that = (IdSprint) o;
        return this.__typename.equals(that.__typename)
         && this.id.equals(that.id);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= id.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<IdSprint> {
      @Override
      public IdSprint map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        return new IdSprint(__typename, id);
      }
    }
  }

  public static class IdEpic {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, false, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @NotNull String id;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public IdEpic(@NotNull String __typename, @NotNull String id) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = Utils.checkNotNull(id, "id == null");
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull String id() {
      return this.id;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "IdEpic{"
          + "__typename=" + __typename + ", "
          + "id=" + id
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof IdEpic) {
        IdEpic that = (IdEpic) o;
        return this.__typename.equals(that.__typename)
         && this.id.equals(that.id);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= id.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<IdEpic> {
      @Override
      public IdEpic map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        return new IdEpic(__typename, id);
      }
    }
  }

  public static class Assignee {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("email", "email", null, false, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @NotNull String email;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Assignee(@NotNull String __typename, @NotNull String email) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.email = Utils.checkNotNull(email, "email == null");
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull String email() {
      return this.email;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], email);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Assignee{"
          + "__typename=" + __typename + ", "
          + "email=" + email
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Assignee) {
        Assignee that = (Assignee) o;
        return this.__typename.equals(that.__typename)
         && this.email.equals(that.email);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= email.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Assignee> {
      @Override
      public Assignee map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String email = reader.readString($responseFields[1]);
        return new Assignee(__typename, email);
      }
    }
  }

  public static class Createdby {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("nama", "nama", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String nama;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Createdby(@NotNull String __typename, @Nullable String nama) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.nama = nama;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String nama() {
      return this.nama;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], nama);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Createdby{"
          + "__typename=" + __typename + ", "
          + "nama=" + nama
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Createdby) {
        Createdby that = (Createdby) o;
        return this.__typename.equals(that.__typename)
         && ((this.nama == null) ? (that.nama == null) : this.nama.equals(that.nama));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (nama == null) ? 0 : nama.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Createdby> {
      @Override
      public Createdby map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String nama = reader.readString($responseFields[1]);
        return new Createdby(__typename, nama);
      }
    }
  }

  public static class Modifiedby {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("nama", "nama", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String nama;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Modifiedby(@NotNull String __typename, @Nullable String nama) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.nama = nama;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String nama() {
      return this.nama;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], nama);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Modifiedby{"
          + "__typename=" + __typename + ", "
          + "nama=" + nama
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Modifiedby) {
        Modifiedby that = (Modifiedby) o;
        return this.__typename.equals(that.__typename)
         && ((this.nama == null) ? (that.nama == null) : this.nama.equals(that.nama));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (nama == null) ? 0 : nama.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Modifiedby> {
      @Override
      public Modifiedby map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String nama = reader.readString($responseFields[1]);
        return new Modifiedby(__typename, nama);
      }
    }
  }
}
