package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.Collections;
import java.util.List;

public final class ProgressQuery implements Query<ProgressQuery.Data, ProgressQuery.Data, Operation.Variables> {
  public static final String OPERATION_ID = "2bb9c6fad081c7ba0af3f891442c1de439cadbafac9f05f7193cd6caf061be4d";

  public static final String QUERY_DOCUMENT = "query Progress {\n"
      + "  progress {\n"
      + "    __typename\n"
      + "    id\n"
      + "    complete\n"
      + "    count\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "Progress";
    }
  };

  private final Variables variables;

  public ProgressQuery() {
    this.variables = Operation.EMPTY_VARIABLES;
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public ProgressQuery.Data wrapData(ProgressQuery.Data data) {
    return data;
  }

  @Override
  public Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    Builder() {
    }

    public ProgressQuery build() {
      return new ProgressQuery();
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forList("progress", "progress", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable List<Progress> progress;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable List<Progress> progress) {
      this.progress = progress;
    }

    public @Nullable List<Progress> progress() {
      return this.progress;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], progress, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Progress) item).marshaller());
              }
            }
          });
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "progress=" + progress
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.progress == null) ? (that.progress == null) : this.progress.equals(that.progress));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (progress == null) ? 0 : progress.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final Progress.Mapper progressFieldMapper = new Progress.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final List<Progress> progress = reader.readList($responseFields[0], new ResponseReader.ListReader<Progress>() {
          @Override
          public Progress read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<Progress>() {
              @Override
              public Progress read(ResponseReader reader) {
                return progressFieldMapper.map(reader);
              }
            });
          }
        });
        return new Data(progress);
      }
    }
  }

  public static class Progress {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("complete", "complete", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("count", "count", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String id;

    final @Nullable Integer complete;

    final @Nullable Integer count;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Progress(@NotNull String __typename, @Nullable String id, @Nullable Integer complete,
        @Nullable Integer count) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = id;
      this.complete = complete;
      this.count = count;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String id() {
      return this.id;
    }

    public @Nullable Integer complete() {
      return this.complete;
    }

    public @Nullable Integer count() {
      return this.count;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
          writer.writeInt($responseFields[2], complete);
          writer.writeInt($responseFields[3], count);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Progress{"
          + "__typename=" + __typename + ", "
          + "id=" + id + ", "
          + "complete=" + complete + ", "
          + "count=" + count
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Progress) {
        Progress that = (Progress) o;
        return this.__typename.equals(that.__typename)
         && ((this.id == null) ? (that.id == null) : this.id.equals(that.id))
         && ((this.complete == null) ? (that.complete == null) : this.complete.equals(that.complete))
         && ((this.count == null) ? (that.count == null) : this.count.equals(that.count));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (id == null) ? 0 : id.hashCode();
        h *= 1000003;
        h ^= (complete == null) ? 0 : complete.hashCode();
        h *= 1000003;
        h ^= (count == null) ? 0 : count.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Progress> {
      @Override
      public Progress map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        final Integer complete = reader.readInt($responseFields[2]);
        final Integer count = reader.readInt($responseFields[3]);
        return new Progress(__typename, id, complete, count);
      }
    }
  }
}
