package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputFieldWriter;
import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public final class RemoveUserMutation implements Mutation<RemoveUserMutation.Data, RemoveUserMutation.Data, RemoveUserMutation.Variables> {
  public static final String OPERATION_ID = "637775fbca1f6962489b8a41df32b08cf85c677a61cfc90c7377ebfe184017b7";

  public static final String QUERY_DOCUMENT = "mutation RemoveUser($idProject: String!, $email: String!) {\n"
      + "  deleteUserproject(idProject: $idProject, email: $email) {\n"
      + "    __typename\n"
      + "    idProject\n"
      + "    email\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "RemoveUser";
    }
  };

  private final RemoveUserMutation.Variables variables;

  public RemoveUserMutation(@NotNull String idProject, @NotNull String email) {
    Utils.checkNotNull(idProject, "idProject == null");
    Utils.checkNotNull(email, "email == null");
    variables = new RemoveUserMutation.Variables(idProject, email);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public RemoveUserMutation.Data wrapData(RemoveUserMutation.Data data) {
    return data;
  }

  @Override
  public RemoveUserMutation.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    private @NotNull String idProject;

    private @NotNull String email;

    Builder() {
    }

    public Builder idProject(@NotNull String idProject) {
      this.idProject = idProject;
      return this;
    }

    public Builder email(@NotNull String email) {
      this.email = email;
      return this;
    }

    public RemoveUserMutation build() {
      Utils.checkNotNull(idProject, "idProject == null");
      Utils.checkNotNull(email, "email == null");
      return new RemoveUserMutation(idProject, email);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull String idProject;

    private final @NotNull String email;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull String idProject, @NotNull String email) {
      this.idProject = idProject;
      this.email = email;
      this.valueMap.put("idProject", idProject);
      this.valueMap.put("email", email);
    }

    public @NotNull String idProject() {
      return idProject;
    }

    public @NotNull String email() {
      return email;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeString("idProject", idProject);
          writer.writeString("email", email);
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forObject("deleteUserproject", "deleteUserproject", new UnmodifiableMapBuilder<String, Object>(2)
      .put("idProject", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "idProject")
        .build())
      .put("email", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "email")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable DeleteUserproject deleteUserproject;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable DeleteUserproject deleteUserproject) {
      this.deleteUserproject = deleteUserproject;
    }

    public @Nullable DeleteUserproject deleteUserproject() {
      return this.deleteUserproject;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeObject($responseFields[0], deleteUserproject != null ? deleteUserproject.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "deleteUserproject=" + deleteUserproject
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.deleteUserproject == null) ? (that.deleteUserproject == null) : this.deleteUserproject.equals(that.deleteUserproject));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (deleteUserproject == null) ? 0 : deleteUserproject.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final DeleteUserproject.Mapper deleteUserprojectFieldMapper = new DeleteUserproject.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final DeleteUserproject deleteUserproject = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<DeleteUserproject>() {
          @Override
          public DeleteUserproject read(ResponseReader reader) {
            return deleteUserprojectFieldMapper.map(reader);
          }
        });
        return new Data(deleteUserproject);
      }
    }
  }

  public static class DeleteUserproject {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("idProject", "idProject", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("email", "email", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String idProject;

    final @Nullable String email;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public DeleteUserproject(@NotNull String __typename, @Nullable String idProject,
        @Nullable String email) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.idProject = idProject;
      this.email = email;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String idProject() {
      return this.idProject;
    }

    public @Nullable String email() {
      return this.email;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], idProject);
          writer.writeString($responseFields[2], email);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "DeleteUserproject{"
          + "__typename=" + __typename + ", "
          + "idProject=" + idProject + ", "
          + "email=" + email
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof DeleteUserproject) {
        DeleteUserproject that = (DeleteUserproject) o;
        return this.__typename.equals(that.__typename)
         && ((this.idProject == null) ? (that.idProject == null) : this.idProject.equals(that.idProject))
         && ((this.email == null) ? (that.email == null) : this.email.equals(that.email));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (idProject == null) ? 0 : idProject.hashCode();
        h *= 1000003;
        h ^= (email == null) ? 0 : email.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<DeleteUserproject> {
      @Override
      public DeleteUserproject map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String idProject = reader.readString($responseFields[1]);
        final String email = reader.readString($responseFields[2]);
        return new DeleteUserproject(__typename, idProject, email);
      }
    }
  }
}
