package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputFieldWriter;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import type.CustomType;

public final class SprinterQuery implements Query<SprinterQuery.Data, SprinterQuery.Data, SprinterQuery.Variables> {
  public static final String OPERATION_ID = "f604a94965956cdc402c5b59e00e22bc82126e0231e8be86dd10eb13e3cc93d6";

  public static final String QUERY_DOCUMENT = "query Sprinter($id: String!) {\n"
      + "  sprint(id: $id) {\n"
      + "    __typename\n"
      + "    id\n"
      + "    name\n"
      + "    begindate\n"
      + "    enddate\n"
      + "    goal\n"
      + "    status\n"
      + "    retrospective\n"
      + "    createddate\n"
      + "    createdby {\n"
      + "      __typename\n"
      + "      nama\n"
      + "    }\n"
      + "    modifieddate\n"
      + "    modifiedby {\n"
      + "      __typename\n"
      + "      nama\n"
      + "    }\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "Sprinter";
    }
  };

  private final SprinterQuery.Variables variables;

  public SprinterQuery(@NotNull String id) {
    Utils.checkNotNull(id, "id == null");
    variables = new SprinterQuery.Variables(id);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public SprinterQuery.Data wrapData(SprinterQuery.Data data) {
    return data;
  }

  @Override
  public SprinterQuery.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    private @NotNull String id;

    Builder() {
    }

    public Builder id(@NotNull String id) {
      this.id = id;
      return this;
    }

    public SprinterQuery build() {
      Utils.checkNotNull(id, "id == null");
      return new SprinterQuery(id);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull String id;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull String id) {
      this.id = id;
      this.valueMap.put("id", id);
    }

    public @NotNull String id() {
      return id;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeString("id", id);
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forList("sprint", "sprint", new UnmodifiableMapBuilder<String, Object>(1)
      .put("id", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "id")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable List<Sprint> sprint;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable List<Sprint> sprint) {
      this.sprint = sprint;
    }

    public @Nullable List<Sprint> sprint() {
      return this.sprint;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], sprint, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((Sprint) item).marshaller());
              }
            }
          });
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "sprint=" + sprint
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.sprint == null) ? (that.sprint == null) : this.sprint.equals(that.sprint));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (sprint == null) ? 0 : sprint.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final Sprint.Mapper sprintFieldMapper = new Sprint.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final List<Sprint> sprint = reader.readList($responseFields[0], new ResponseReader.ListReader<Sprint>() {
          @Override
          public Sprint read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<Sprint>() {
              @Override
              public Sprint read(ResponseReader reader) {
                return sprintFieldMapper.map(reader);
              }
            });
          }
        });
        return new Data(sprint);
      }
    }
  }

  public static class Sprint {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("name", "name", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("begindate", "begindate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("enddate", "enddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("goal", "goal", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("status", "status", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("retrospective", "retrospective", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("createddate", "createddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("createdby", "createdby", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("modifieddate", "modifieddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("modifiedby", "modifiedby", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @NotNull String id;

    final @Nullable String name;

    final @Nullable Date begindate;

    final @Nullable Date enddate;

    final @Nullable String goal;

    final @Nullable String status;

    final @Nullable String retrospective;

    final @Nullable Date createddate;

    final @Nullable Createdby createdby;

    final @Nullable Date modifieddate;

    final @Nullable Modifiedby modifiedby;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Sprint(@NotNull String __typename, @NotNull String id, @Nullable String name,
        @Nullable Date begindate, @Nullable Date enddate, @Nullable String goal,
        @Nullable String status, @Nullable String retrospective, @Nullable Date createddate,
        @Nullable Createdby createdby, @Nullable Date modifieddate,
        @Nullable Modifiedby modifiedby) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = Utils.checkNotNull(id, "id == null");
      this.name = name;
      this.begindate = begindate;
      this.enddate = enddate;
      this.goal = goal;
      this.status = status;
      this.retrospective = retrospective;
      this.createddate = createddate;
      this.createdby = createdby;
      this.modifieddate = modifieddate;
      this.modifiedby = modifiedby;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull String id() {
      return this.id;
    }

    public @Nullable String name() {
      return this.name;
    }

    public @Nullable Date begindate() {
      return this.begindate;
    }

    public @Nullable Date enddate() {
      return this.enddate;
    }

    public @Nullable String goal() {
      return this.goal;
    }

    public @Nullable String status() {
      return this.status;
    }

    public @Nullable String retrospective() {
      return this.retrospective;
    }

    public @Nullable Date createddate() {
      return this.createddate;
    }

    public @Nullable Createdby createdby() {
      return this.createdby;
    }

    public @Nullable Date modifieddate() {
      return this.modifieddate;
    }

    public @Nullable Modifiedby modifiedby() {
      return this.modifiedby;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
          writer.writeString($responseFields[2], name);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[3], begindate);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[4], enddate);
          writer.writeString($responseFields[5], goal);
          writer.writeString($responseFields[6], status);
          writer.writeString($responseFields[7], retrospective);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[8], createddate);
          writer.writeObject($responseFields[9], createdby != null ? createdby.marshaller() : null);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[10], modifieddate);
          writer.writeObject($responseFields[11], modifiedby != null ? modifiedby.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Sprint{"
          + "__typename=" + __typename + ", "
          + "id=" + id + ", "
          + "name=" + name + ", "
          + "begindate=" + begindate + ", "
          + "enddate=" + enddate + ", "
          + "goal=" + goal + ", "
          + "status=" + status + ", "
          + "retrospective=" + retrospective + ", "
          + "createddate=" + createddate + ", "
          + "createdby=" + createdby + ", "
          + "modifieddate=" + modifieddate + ", "
          + "modifiedby=" + modifiedby
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Sprint) {
        Sprint that = (Sprint) o;
        return this.__typename.equals(that.__typename)
         && this.id.equals(that.id)
         && ((this.name == null) ? (that.name == null) : this.name.equals(that.name))
         && ((this.begindate == null) ? (that.begindate == null) : this.begindate.equals(that.begindate))
         && ((this.enddate == null) ? (that.enddate == null) : this.enddate.equals(that.enddate))
         && ((this.goal == null) ? (that.goal == null) : this.goal.equals(that.goal))
         && ((this.status == null) ? (that.status == null) : this.status.equals(that.status))
         && ((this.retrospective == null) ? (that.retrospective == null) : this.retrospective.equals(that.retrospective))
         && ((this.createddate == null) ? (that.createddate == null) : this.createddate.equals(that.createddate))
         && ((this.createdby == null) ? (that.createdby == null) : this.createdby.equals(that.createdby))
         && ((this.modifieddate == null) ? (that.modifieddate == null) : this.modifieddate.equals(that.modifieddate))
         && ((this.modifiedby == null) ? (that.modifiedby == null) : this.modifiedby.equals(that.modifiedby));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= id.hashCode();
        h *= 1000003;
        h ^= (name == null) ? 0 : name.hashCode();
        h *= 1000003;
        h ^= (begindate == null) ? 0 : begindate.hashCode();
        h *= 1000003;
        h ^= (enddate == null) ? 0 : enddate.hashCode();
        h *= 1000003;
        h ^= (goal == null) ? 0 : goal.hashCode();
        h *= 1000003;
        h ^= (status == null) ? 0 : status.hashCode();
        h *= 1000003;
        h ^= (retrospective == null) ? 0 : retrospective.hashCode();
        h *= 1000003;
        h ^= (createddate == null) ? 0 : createddate.hashCode();
        h *= 1000003;
        h ^= (createdby == null) ? 0 : createdby.hashCode();
        h *= 1000003;
        h ^= (modifieddate == null) ? 0 : modifieddate.hashCode();
        h *= 1000003;
        h ^= (modifiedby == null) ? 0 : modifiedby.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Sprint> {
      final Createdby.Mapper createdbyFieldMapper = new Createdby.Mapper();

      final Modifiedby.Mapper modifiedbyFieldMapper = new Modifiedby.Mapper();

      @Override
      public Sprint map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        final String name = reader.readString($responseFields[2]);
        final Date begindate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[3]);
        final Date enddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[4]);
        final String goal = reader.readString($responseFields[5]);
        final String status = reader.readString($responseFields[6]);
        final String retrospective = reader.readString($responseFields[7]);
        final Date createddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[8]);
        final Createdby createdby = reader.readObject($responseFields[9], new ResponseReader.ObjectReader<Createdby>() {
          @Override
          public Createdby read(ResponseReader reader) {
            return createdbyFieldMapper.map(reader);
          }
        });
        final Date modifieddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[10]);
        final Modifiedby modifiedby = reader.readObject($responseFields[11], new ResponseReader.ObjectReader<Modifiedby>() {
          @Override
          public Modifiedby read(ResponseReader reader) {
            return modifiedbyFieldMapper.map(reader);
          }
        });
        return new Sprint(__typename, id, name, begindate, enddate, goal, status, retrospective, createddate, createdby, modifieddate, modifiedby);
      }
    }
  }

  public static class Createdby {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("nama", "nama", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String nama;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Createdby(@NotNull String __typename, @Nullable String nama) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.nama = nama;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String nama() {
      return this.nama;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], nama);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Createdby{"
          + "__typename=" + __typename + ", "
          + "nama=" + nama
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Createdby) {
        Createdby that = (Createdby) o;
        return this.__typename.equals(that.__typename)
         && ((this.nama == null) ? (that.nama == null) : this.nama.equals(that.nama));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (nama == null) ? 0 : nama.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Createdby> {
      @Override
      public Createdby map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String nama = reader.readString($responseFields[1]);
        return new Createdby(__typename, nama);
      }
    }
  }

  public static class Modifiedby {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("nama", "nama", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String nama;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Modifiedby(@NotNull String __typename, @Nullable String nama) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.nama = nama;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String nama() {
      return this.nama;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], nama);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Modifiedby{"
          + "__typename=" + __typename + ", "
          + "nama=" + nama
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Modifiedby) {
        Modifiedby that = (Modifiedby) o;
        return this.__typename.equals(that.__typename)
         && ((this.nama == null) ? (that.nama == null) : this.nama.equals(that.nama));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (nama == null) ? 0 : nama.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Modifiedby> {
      @Override
      public Modifiedby map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String nama = reader.readString($responseFields[1]);
        return new Modifiedby(__typename, nama);
      }
    }
  }
}
