package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputFieldWriter;
import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import type.CustomType;

public final class SprintMutation implements Mutation<SprintMutation.Data, SprintMutation.Data, SprintMutation.Variables> {
  public static final String OPERATION_ID = "abb464eb74000a1131099a476dc918297828854addb69034cadd987cd71864b7";

  public static final String QUERY_DOCUMENT = "mutation Sprint($id: String!, $idProject: String!, $name: String!, $goal: String!, $status: String!, $createddate: Date!, $createdby: String!) {\n"
      + "  createSprint(id: $id, idProject: $idProject, name: $name, goal: $goal, status: $status, createddate: $createddate, createdby: $createdby) {\n"
      + "    __typename\n"
      + "    id\n"
      + "    idProject\n"
      + "    name\n"
      + "    goal\n"
      + "    status\n"
      + "    createddate\n"
      + "    createdby\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "Sprint";
    }
  };

  private final SprintMutation.Variables variables;

  public SprintMutation(@NotNull String id, @NotNull String idProject, @NotNull String name,
      @NotNull String goal, @NotNull String status, @NotNull Date createddate,
      @NotNull String createdby) {
    Utils.checkNotNull(id, "id == null");
    Utils.checkNotNull(idProject, "idProject == null");
    Utils.checkNotNull(name, "name == null");
    Utils.checkNotNull(goal, "goal == null");
    Utils.checkNotNull(status, "status == null");
    Utils.checkNotNull(createddate, "createddate == null");
    Utils.checkNotNull(createdby, "createdby == null");
    variables = new SprintMutation.Variables(id, idProject, name, goal, status, createddate, createdby);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public SprintMutation.Data wrapData(SprintMutation.Data data) {
    return data;
  }

  @Override
  public SprintMutation.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    private @NotNull String id;

    private @NotNull String idProject;

    private @NotNull String name;

    private @NotNull String goal;

    private @NotNull String status;

    private @NotNull Date createddate;

    private @NotNull String createdby;

    Builder() {
    }

    public Builder id(@NotNull String id) {
      this.id = id;
      return this;
    }

    public Builder idProject(@NotNull String idProject) {
      this.idProject = idProject;
      return this;
    }

    public Builder name(@NotNull String name) {
      this.name = name;
      return this;
    }

    public Builder goal(@NotNull String goal) {
      this.goal = goal;
      return this;
    }

    public Builder status(@NotNull String status) {
      this.status = status;
      return this;
    }

    public Builder createddate(@NotNull Date createddate) {
      this.createddate = createddate;
      return this;
    }

    public Builder createdby(@NotNull String createdby) {
      this.createdby = createdby;
      return this;
    }

    public SprintMutation build() {
      Utils.checkNotNull(id, "id == null");
      Utils.checkNotNull(idProject, "idProject == null");
      Utils.checkNotNull(name, "name == null");
      Utils.checkNotNull(goal, "goal == null");
      Utils.checkNotNull(status, "status == null");
      Utils.checkNotNull(createddate, "createddate == null");
      Utils.checkNotNull(createdby, "createdby == null");
      return new SprintMutation(id, idProject, name, goal, status, createddate, createdby);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull String id;

    private final @NotNull String idProject;

    private final @NotNull String name;

    private final @NotNull String goal;

    private final @NotNull String status;

    private final @NotNull Date createddate;

    private final @NotNull String createdby;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull String id, @NotNull String idProject, @NotNull String name,
        @NotNull String goal, @NotNull String status, @NotNull Date createddate,
        @NotNull String createdby) {
      this.id = id;
      this.idProject = idProject;
      this.name = name;
      this.goal = goal;
      this.status = status;
      this.createddate = createddate;
      this.createdby = createdby;
      this.valueMap.put("id", id);
      this.valueMap.put("idProject", idProject);
      this.valueMap.put("name", name);
      this.valueMap.put("goal", goal);
      this.valueMap.put("status", status);
      this.valueMap.put("createddate", createddate);
      this.valueMap.put("createdby", createdby);
    }

    public @NotNull String id() {
      return id;
    }

    public @NotNull String idProject() {
      return idProject;
    }

    public @NotNull String name() {
      return name;
    }

    public @NotNull String goal() {
      return goal;
    }

    public @NotNull String status() {
      return status;
    }

    public @NotNull Date createddate() {
      return createddate;
    }

    public @NotNull String createdby() {
      return createdby;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeString("id", id);
          writer.writeString("idProject", idProject);
          writer.writeString("name", name);
          writer.writeString("goal", goal);
          writer.writeString("status", status);
          writer.writeCustom("createddate", CustomType.DATE, createddate);
          writer.writeString("createdby", createdby);
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forObject("createSprint", "createSprint", new UnmodifiableMapBuilder<String, Object>(7)
      .put("id", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "id")
        .build())
      .put("idProject", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "idProject")
        .build())
      .put("name", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "name")
        .build())
      .put("goal", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "goal")
        .build())
      .put("status", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "status")
        .build())
      .put("createddate", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "createddate")
        .build())
      .put("createdby", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "createdby")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable CreateSprint createSprint;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable CreateSprint createSprint) {
      this.createSprint = createSprint;
    }

    public @Nullable CreateSprint createSprint() {
      return this.createSprint;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeObject($responseFields[0], createSprint != null ? createSprint.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "createSprint=" + createSprint
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.createSprint == null) ? (that.createSprint == null) : this.createSprint.equals(that.createSprint));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (createSprint == null) ? 0 : createSprint.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final CreateSprint.Mapper createSprintFieldMapper = new CreateSprint.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final CreateSprint createSprint = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<CreateSprint>() {
          @Override
          public CreateSprint read(ResponseReader reader) {
            return createSprintFieldMapper.map(reader);
          }
        });
        return new Data(createSprint);
      }
    }
  }

  public static class CreateSprint {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("idProject", "idProject", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("name", "name", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("goal", "goal", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("status", "status", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("createddate", "createddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("createdby", "createdby", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String id;

    final @Nullable String idProject;

    final @Nullable String name;

    final @Nullable String goal;

    final @Nullable String status;

    final @Nullable Date createddate;

    final @Nullable String createdby;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public CreateSprint(@NotNull String __typename, @Nullable String id, @Nullable String idProject,
        @Nullable String name, @Nullable String goal, @Nullable String status,
        @Nullable Date createddate, @Nullable String createdby) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = id;
      this.idProject = idProject;
      this.name = name;
      this.goal = goal;
      this.status = status;
      this.createddate = createddate;
      this.createdby = createdby;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String id() {
      return this.id;
    }

    public @Nullable String idProject() {
      return this.idProject;
    }

    public @Nullable String name() {
      return this.name;
    }

    public @Nullable String goal() {
      return this.goal;
    }

    public @Nullable String status() {
      return this.status;
    }

    public @Nullable Date createddate() {
      return this.createddate;
    }

    public @Nullable String createdby() {
      return this.createdby;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
          writer.writeString($responseFields[2], idProject);
          writer.writeString($responseFields[3], name);
          writer.writeString($responseFields[4], goal);
          writer.writeString($responseFields[5], status);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[6], createddate);
          writer.writeString($responseFields[7], createdby);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "CreateSprint{"
          + "__typename=" + __typename + ", "
          + "id=" + id + ", "
          + "idProject=" + idProject + ", "
          + "name=" + name + ", "
          + "goal=" + goal + ", "
          + "status=" + status + ", "
          + "createddate=" + createddate + ", "
          + "createdby=" + createdby
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof CreateSprint) {
        CreateSprint that = (CreateSprint) o;
        return this.__typename.equals(that.__typename)
         && ((this.id == null) ? (that.id == null) : this.id.equals(that.id))
         && ((this.idProject == null) ? (that.idProject == null) : this.idProject.equals(that.idProject))
         && ((this.name == null) ? (that.name == null) : this.name.equals(that.name))
         && ((this.goal == null) ? (that.goal == null) : this.goal.equals(that.goal))
         && ((this.status == null) ? (that.status == null) : this.status.equals(that.status))
         && ((this.createddate == null) ? (that.createddate == null) : this.createddate.equals(that.createddate))
         && ((this.createdby == null) ? (that.createdby == null) : this.createdby.equals(that.createdby));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (id == null) ? 0 : id.hashCode();
        h *= 1000003;
        h ^= (idProject == null) ? 0 : idProject.hashCode();
        h *= 1000003;
        h ^= (name == null) ? 0 : name.hashCode();
        h *= 1000003;
        h ^= (goal == null) ? 0 : goal.hashCode();
        h *= 1000003;
        h ^= (status == null) ? 0 : status.hashCode();
        h *= 1000003;
        h ^= (createddate == null) ? 0 : createddate.hashCode();
        h *= 1000003;
        h ^= (createdby == null) ? 0 : createdby.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<CreateSprint> {
      @Override
      public CreateSprint map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        final String idProject = reader.readString($responseFields[2]);
        final String name = reader.readString($responseFields[3]);
        final String goal = reader.readString($responseFields[4]);
        final String status = reader.readString($responseFields[5]);
        final Date createddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[6]);
        final String createdby = reader.readString($responseFields[7]);
        return new CreateSprint(__typename, id, idProject, name, goal, status, createddate, createdby);
      }
    }
  }
}
