package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputFieldWriter;
import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import type.CustomType;

public final class SprintEditMutation implements Mutation<SprintEditMutation.Data, SprintEditMutation.Data, SprintEditMutation.Variables> {
  public static final String OPERATION_ID = "f333c5e23c47dafcd6cb05de352303e8dcfea6deedafe30407a203c3b3cd5cf1";

  public static final String QUERY_DOCUMENT = "mutation SprintEdit($id: String!, $name: String!, $begindate: Date!, $enddate: Date!, $goal: String!, $status: String!, $retrospective: String!, $modifieddate: Date!, $modifiedby: String!) {\n"
      + "  editSprint(id: $id, name: $name, begindate: $begindate, enddate: $enddate, goal: $goal, status: $status, retrospective: $retrospective, modifieddate: $modifieddate, modifiedby: $modifiedby) {\n"
      + "    __typename\n"
      + "    id\n"
      + "    name\n"
      + "    begindate\n"
      + "    enddate\n"
      + "    goal\n"
      + "    status\n"
      + "    retrospective\n"
      + "    modifieddate\n"
      + "    modifiedby\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "SprintEdit";
    }
  };

  private final SprintEditMutation.Variables variables;

  public SprintEditMutation(@NotNull String id, @NotNull String name, @NotNull Date begindate,
      @NotNull Date enddate, @NotNull String goal, @NotNull String status,
      @NotNull String retrospective, @NotNull Date modifieddate, @NotNull String modifiedby) {
    Utils.checkNotNull(id, "id == null");
    Utils.checkNotNull(name, "name == null");
    Utils.checkNotNull(begindate, "begindate == null");
    Utils.checkNotNull(enddate, "enddate == null");
    Utils.checkNotNull(goal, "goal == null");
    Utils.checkNotNull(status, "status == null");
    Utils.checkNotNull(retrospective, "retrospective == null");
    Utils.checkNotNull(modifieddate, "modifieddate == null");
    Utils.checkNotNull(modifiedby, "modifiedby == null");
    variables = new SprintEditMutation.Variables(id, name, begindate, enddate, goal, status, retrospective, modifieddate, modifiedby);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public SprintEditMutation.Data wrapData(SprintEditMutation.Data data) {
    return data;
  }

  @Override
  public SprintEditMutation.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    private @NotNull String id;

    private @NotNull String name;

    private @NotNull Date begindate;

    private @NotNull Date enddate;

    private @NotNull String goal;

    private @NotNull String status;

    private @NotNull String retrospective;

    private @NotNull Date modifieddate;

    private @NotNull String modifiedby;

    Builder() {
    }

    public Builder id(@NotNull String id) {
      this.id = id;
      return this;
    }

    public Builder name(@NotNull String name) {
      this.name = name;
      return this;
    }

    public Builder begindate(@NotNull Date begindate) {
      this.begindate = begindate;
      return this;
    }

    public Builder enddate(@NotNull Date enddate) {
      this.enddate = enddate;
      return this;
    }

    public Builder goal(@NotNull String goal) {
      this.goal = goal;
      return this;
    }

    public Builder status(@NotNull String status) {
      this.status = status;
      return this;
    }

    public Builder retrospective(@NotNull String retrospective) {
      this.retrospective = retrospective;
      return this;
    }

    public Builder modifieddate(@NotNull Date modifieddate) {
      this.modifieddate = modifieddate;
      return this;
    }

    public Builder modifiedby(@NotNull String modifiedby) {
      this.modifiedby = modifiedby;
      return this;
    }

    public SprintEditMutation build() {
      Utils.checkNotNull(id, "id == null");
      Utils.checkNotNull(name, "name == null");
      Utils.checkNotNull(begindate, "begindate == null");
      Utils.checkNotNull(enddate, "enddate == null");
      Utils.checkNotNull(goal, "goal == null");
      Utils.checkNotNull(status, "status == null");
      Utils.checkNotNull(retrospective, "retrospective == null");
      Utils.checkNotNull(modifieddate, "modifieddate == null");
      Utils.checkNotNull(modifiedby, "modifiedby == null");
      return new SprintEditMutation(id, name, begindate, enddate, goal, status, retrospective, modifieddate, modifiedby);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull String id;

    private final @NotNull String name;

    private final @NotNull Date begindate;

    private final @NotNull Date enddate;

    private final @NotNull String goal;

    private final @NotNull String status;

    private final @NotNull String retrospective;

    private final @NotNull Date modifieddate;

    private final @NotNull String modifiedby;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull String id, @NotNull String name, @NotNull Date begindate,
        @NotNull Date enddate, @NotNull String goal, @NotNull String status,
        @NotNull String retrospective, @NotNull Date modifieddate, @NotNull String modifiedby) {
      this.id = id;
      this.name = name;
      this.begindate = begindate;
      this.enddate = enddate;
      this.goal = goal;
      this.status = status;
      this.retrospective = retrospective;
      this.modifieddate = modifieddate;
      this.modifiedby = modifiedby;
      this.valueMap.put("id", id);
      this.valueMap.put("name", name);
      this.valueMap.put("begindate", begindate);
      this.valueMap.put("enddate", enddate);
      this.valueMap.put("goal", goal);
      this.valueMap.put("status", status);
      this.valueMap.put("retrospective", retrospective);
      this.valueMap.put("modifieddate", modifieddate);
      this.valueMap.put("modifiedby", modifiedby);
    }

    public @NotNull String id() {
      return id;
    }

    public @NotNull String name() {
      return name;
    }

    public @NotNull Date begindate() {
      return begindate;
    }

    public @NotNull Date enddate() {
      return enddate;
    }

    public @NotNull String goal() {
      return goal;
    }

    public @NotNull String status() {
      return status;
    }

    public @NotNull String retrospective() {
      return retrospective;
    }

    public @NotNull Date modifieddate() {
      return modifieddate;
    }

    public @NotNull String modifiedby() {
      return modifiedby;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeString("id", id);
          writer.writeString("name", name);
          writer.writeCustom("begindate", CustomType.DATE, begindate);
          writer.writeCustom("enddate", CustomType.DATE, enddate);
          writer.writeString("goal", goal);
          writer.writeString("status", status);
          writer.writeString("retrospective", retrospective);
          writer.writeCustom("modifieddate", CustomType.DATE, modifieddate);
          writer.writeString("modifiedby", modifiedby);
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forObject("editSprint", "editSprint", new UnmodifiableMapBuilder<String, Object>(9)
      .put("id", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "id")
        .build())
      .put("name", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "name")
        .build())
      .put("begindate", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "begindate")
        .build())
      .put("enddate", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "enddate")
        .build())
      .put("goal", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "goal")
        .build())
      .put("status", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "status")
        .build())
      .put("retrospective", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "retrospective")
        .build())
      .put("modifieddate", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "modifieddate")
        .build())
      .put("modifiedby", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "modifiedby")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable EditSprint editSprint;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable EditSprint editSprint) {
      this.editSprint = editSprint;
    }

    public @Nullable EditSprint editSprint() {
      return this.editSprint;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeObject($responseFields[0], editSprint != null ? editSprint.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "editSprint=" + editSprint
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.editSprint == null) ? (that.editSprint == null) : this.editSprint.equals(that.editSprint));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (editSprint == null) ? 0 : editSprint.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final EditSprint.Mapper editSprintFieldMapper = new EditSprint.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final EditSprint editSprint = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<EditSprint>() {
          @Override
          public EditSprint read(ResponseReader reader) {
            return editSprintFieldMapper.map(reader);
          }
        });
        return new Data(editSprint);
      }
    }
  }

  public static class EditSprint {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("id", "id", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("name", "name", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("begindate", "begindate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("enddate", "enddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("goal", "goal", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("status", "status", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("retrospective", "retrospective", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("modifieddate", "modifieddate", null, true, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("modifiedby", "modifiedby", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable String id;

    final @Nullable String name;

    final @Nullable Date begindate;

    final @Nullable Date enddate;

    final @Nullable String goal;

    final @Nullable String status;

    final @Nullable String retrospective;

    final @Nullable Date modifieddate;

    final @Nullable String modifiedby;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public EditSprint(@NotNull String __typename, @Nullable String id, @Nullable String name,
        @Nullable Date begindate, @Nullable Date enddate, @Nullable String goal,
        @Nullable String status, @Nullable String retrospective, @Nullable Date modifieddate,
        @Nullable String modifiedby) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.id = id;
      this.name = name;
      this.begindate = begindate;
      this.enddate = enddate;
      this.goal = goal;
      this.status = status;
      this.retrospective = retrospective;
      this.modifieddate = modifieddate;
      this.modifiedby = modifiedby;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable String id() {
      return this.id;
    }

    public @Nullable String name() {
      return this.name;
    }

    public @Nullable Date begindate() {
      return this.begindate;
    }

    public @Nullable Date enddate() {
      return this.enddate;
    }

    public @Nullable String goal() {
      return this.goal;
    }

    public @Nullable String status() {
      return this.status;
    }

    public @Nullable String retrospective() {
      return this.retrospective;
    }

    public @Nullable Date modifieddate() {
      return this.modifieddate;
    }

    public @Nullable String modifiedby() {
      return this.modifiedby;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], id);
          writer.writeString($responseFields[2], name);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[3], begindate);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[4], enddate);
          writer.writeString($responseFields[5], goal);
          writer.writeString($responseFields[6], status);
          writer.writeString($responseFields[7], retrospective);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[8], modifieddate);
          writer.writeString($responseFields[9], modifiedby);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "EditSprint{"
          + "__typename=" + __typename + ", "
          + "id=" + id + ", "
          + "name=" + name + ", "
          + "begindate=" + begindate + ", "
          + "enddate=" + enddate + ", "
          + "goal=" + goal + ", "
          + "status=" + status + ", "
          + "retrospective=" + retrospective + ", "
          + "modifieddate=" + modifieddate + ", "
          + "modifiedby=" + modifiedby
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof EditSprint) {
        EditSprint that = (EditSprint) o;
        return this.__typename.equals(that.__typename)
         && ((this.id == null) ? (that.id == null) : this.id.equals(that.id))
         && ((this.name == null) ? (that.name == null) : this.name.equals(that.name))
         && ((this.begindate == null) ? (that.begindate == null) : this.begindate.equals(that.begindate))
         && ((this.enddate == null) ? (that.enddate == null) : this.enddate.equals(that.enddate))
         && ((this.goal == null) ? (that.goal == null) : this.goal.equals(that.goal))
         && ((this.status == null) ? (that.status == null) : this.status.equals(that.status))
         && ((this.retrospective == null) ? (that.retrospective == null) : this.retrospective.equals(that.retrospective))
         && ((this.modifieddate == null) ? (that.modifieddate == null) : this.modifieddate.equals(that.modifieddate))
         && ((this.modifiedby == null) ? (that.modifiedby == null) : this.modifiedby.equals(that.modifiedby));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (id == null) ? 0 : id.hashCode();
        h *= 1000003;
        h ^= (name == null) ? 0 : name.hashCode();
        h *= 1000003;
        h ^= (begindate == null) ? 0 : begindate.hashCode();
        h *= 1000003;
        h ^= (enddate == null) ? 0 : enddate.hashCode();
        h *= 1000003;
        h ^= (goal == null) ? 0 : goal.hashCode();
        h *= 1000003;
        h ^= (status == null) ? 0 : status.hashCode();
        h *= 1000003;
        h ^= (retrospective == null) ? 0 : retrospective.hashCode();
        h *= 1000003;
        h ^= (modifieddate == null) ? 0 : modifieddate.hashCode();
        h *= 1000003;
        h ^= (modifiedby == null) ? 0 : modifiedby.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<EditSprint> {
      @Override
      public EditSprint map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String id = reader.readString($responseFields[1]);
        final String name = reader.readString($responseFields[2]);
        final Date begindate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[3]);
        final Date enddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[4]);
        final String goal = reader.readString($responseFields[5]);
        final String status = reader.readString($responseFields[6]);
        final String retrospective = reader.readString($responseFields[7]);
        final Date modifieddate = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[8]);
        final String modifiedby = reader.readString($responseFields[9]);
        return new EditSprint(__typename, id, name, begindate, enddate, goal, status, retrospective, modifieddate, modifiedby);
      }
    }
  }
}
