package com.example.app;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputFieldWriter;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ResponseFieldMapper;
import com.apollographql.apollo.api.ResponseFieldMarshaller;
import com.apollographql.apollo.api.ResponseReader;
import com.apollographql.apollo.api.ResponseWriter;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class UserLoginQuery implements Query<UserLoginQuery.Data, UserLoginQuery.Data, UserLoginQuery.Variables> {
  public static final String OPERATION_ID = "7f89cfa9810bdbcc3fc4738790d24725b3506a234561770bafecabde7d9dcaa0";

  public static final String QUERY_DOCUMENT = "query UserLogin($email: String!, $password: String!) {\n"
      + "  user(email: $email, password: $password) {\n"
      + "    __typename\n"
      + "    email\n"
      + "    nama\n"
      + "    password\n"
      + "    role\n"
      + "  }\n"
      + "}";

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "UserLogin";
    }
  };

  private final UserLoginQuery.Variables variables;

  public UserLoginQuery(@NotNull String email, @NotNull String password) {
    Utils.checkNotNull(email, "email == null");
    Utils.checkNotNull(password, "password == null");
    variables = new UserLoginQuery.Variables(email, password);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public UserLoginQuery.Data wrapData(UserLoginQuery.Data data) {
    return data;
  }

  @Override
  public UserLoginQuery.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  public static final class Builder {
    private @NotNull String email;

    private @NotNull String password;

    Builder() {
    }

    public Builder email(@NotNull String email) {
      this.email = email;
      return this;
    }

    public Builder password(@NotNull String password) {
      this.password = password;
      return this;
    }

    public UserLoginQuery build() {
      Utils.checkNotNull(email, "email == null");
      Utils.checkNotNull(password, "password == null");
      return new UserLoginQuery(email, password);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull String email;

    private final @NotNull String password;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull String email, @NotNull String password) {
      this.email = email;
      this.password = password;
      this.valueMap.put("email", email);
      this.valueMap.put("password", password);
    }

    public @NotNull String email() {
      return email;
    }

    public @NotNull String password() {
      return password;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeString("email", email);
          writer.writeString("password", password);
        }
      };
    }
  }

  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forList("user", "user", new UnmodifiableMapBuilder<String, Object>(2)
      .put("email", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "email")
        .build())
      .put("password", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "password")
        .build())
      .build(), true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable List<User> user;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable List<User> user) {
      this.user = user;
    }

    public @Nullable List<User> user() {
      return this.user;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], user, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((User) item).marshaller());
              }
            }
          });
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "user=" + user
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.user == null) ? (that.user == null) : this.user.equals(that.user));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (user == null) ? 0 : user.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final User.Mapper userFieldMapper = new User.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final List<User> user = reader.readList($responseFields[0], new ResponseReader.ListReader<User>() {
          @Override
          public User read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<User>() {
              @Override
              public User read(ResponseReader reader) {
                return userFieldMapper.map(reader);
              }
            });
          }
        });
        return new Data(user);
      }
    }
  }

  public static class User {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("email", "email", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("nama", "nama", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("password", "password", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("role", "role", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @NotNull String email;

    final @Nullable String nama;

    final @Nullable String password;

    final @Nullable String role;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public User(@NotNull String __typename, @NotNull String email, @Nullable String nama,
        @Nullable String password, @Nullable String role) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.email = Utils.checkNotNull(email, "email == null");
      this.nama = nama;
      this.password = password;
      this.role = role;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull String email() {
      return this.email;
    }

    public @Nullable String nama() {
      return this.nama;
    }

    public @Nullable String password() {
      return this.password;
    }

    public @Nullable String role() {
      return this.role;
    }

    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], email);
          writer.writeString($responseFields[2], nama);
          writer.writeString($responseFields[3], password);
          writer.writeString($responseFields[4], role);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "User{"
          + "__typename=" + __typename + ", "
          + "email=" + email + ", "
          + "nama=" + nama + ", "
          + "password=" + password + ", "
          + "role=" + role
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof User) {
        User that = (User) o;
        return this.__typename.equals(that.__typename)
         && this.email.equals(that.email)
         && ((this.nama == null) ? (that.nama == null) : this.nama.equals(that.nama))
         && ((this.password == null) ? (that.password == null) : this.password.equals(that.password))
         && ((this.role == null) ? (that.role == null) : this.role.equals(that.role));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= email.hashCode();
        h *= 1000003;
        h ^= (nama == null) ? 0 : nama.hashCode();
        h *= 1000003;
        h ^= (password == null) ? 0 : password.hashCode();
        h *= 1000003;
        h ^= (role == null) ? 0 : role.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<User> {
      @Override
      public User map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String email = reader.readString($responseFields[1]);
        final String nama = reader.readString($responseFields[2]);
        final String password = reader.readString($responseFields[3]);
        final String role = reader.readString($responseFields[4]);
        return new User(__typename, email, nama, password, role);
      }
    }
  }
}
